-- Seed do catálogo real (mesmos produtos que hoje vivem em src/data/products.ts),
-- para o admin abrir com dados de verdade em vez de vazio.
-- Rode depois de 0001_admin_schema.sql.

insert into public.categories (name, slug, product_type) values
  ('Vestidos', 'vestidos', 'roupa'),
  ('Blusas', 'blusas', 'roupa'),
  ('Calças', 'calcas', 'roupa'),
  ('Saias', 'saias', 'roupa'),
  ('Casacos', 'casacos', 'roupa'),
  ('Conjuntos', 'conjuntos', 'roupa'),
  ('Perfumes', 'perfumes', 'perfume'),
  ('Kits', 'kits', 'perfume'),
  ('Corpo', 'corpo', 'cosmetico'),
  ('Rosto', 'rosto', 'cosmetico'),
  ('Banho', 'banho', 'cosmetico'),
  ('Lábios', 'labios', 'cosmetico')
on conflict (slug) do nothing;

insert into public.products
  (ref, slug, name, category_id, price, compare_at_price, description, stock, is_new, is_bestseller, is_active, sizes, colors, volumes, pyramid, actives, fabric, care)
values
  ('KLS-0001', 'vestido-midi-entardecer', 'Vestido Midi Entardecer',
    (select id from public.categories where slug = 'vestidos'),
    289.90, 349.90,
    'Silhueta fluida em viscose com toque de seda, decote coração e amarração nas costas. Cai como um entardecer sobre a pele — quente, dourado, íntimo.',
    12, false, true, true,
    array['PP','P','M','G','GG'],
    '[{"name":"Ameixa","hex":"#6b3a4a"},{"name":"Terracota","hex":"#9C4F44"}]'::jsonb,
    null, null, null,
    '92% Viscose · 8% Elastano',
    array['Lavar à mão em água fria','Não usar alvejante','Secar à sombra','Passar em temperatura baixa']),

  ('KLS-0002', 'blusa-ombro-a-ombro-rouge', 'Blusa Ombro a Ombro Rouge',
    (select id from public.categories where slug = 'blusas'),
    129.90, null,
    'Ombros expostos, elástico invisível e um tom rouge que aquece o rosto. A peça que resolve o jantar de última hora.',
    20, false, false, true,
    array['PP','P','M','G'],
    '[{"name":"Rouge","hex":"#B0746A"},{"name":"Marfim","hex":"#FAF6F1"}]'::jsonb,
    null, null, null,
    '100% Algodão penteado', null),

  ('KLS-0003', 'calca-wide-leg-alfaiataria', 'Calça Wide Leg Alfaiataria',
    (select id from public.categories where slug = 'calcas'),
    219.90, null,
    'Alfaiataria feminina de cintura alta, pregas frontais e caimento longo que alonga a silhueta. Sofisticada do café ao coquetel.',
    15, false, false, true,
    array['36','38','40','42','44'],
    '[{"name":"Preto","hex":"#2D2A29"},{"name":"Areia","hex":"#c9b39a"}]'::jsonb,
    null, null, null,
    'Tecido de alfaiataria com toque frio', null),

  ('KLS-0004', 'saia-cetim-ameixa', 'Saia Cetim Ameixa',
    (select id from public.categories where slug = 'saias'),
    159.90, null,
    'Cetim líquido cor de ameixa madura, corte enviesado e fenda discreta. Move como se tivesse vida própria.',
    9, true, false, true,
    array['PP','P','M','G'],
    '[{"name":"Ameixa","hex":"#6b3a4a"}]'::jsonb,
    null, null, null,
    'Cetim de viscose', null),

  ('KLS-0005', 'cropped-canelado-nude', 'Cropped Canelado Nude',
    (select id from public.categories where slug = 'blusas'),
    89.90, null,
    'Canelado colado ao corpo em tom nude quente. Base curinga para calças de cintura alta e saias midi.',
    34, false, true, true,
    array['Único'],
    '[{"name":"Nude","hex":"#ECD3CA"},{"name":"Preto","hex":"#2D2A29"},{"name":"Chocolate","hex":"#5a3a2e"}]'::jsonb,
    null, null, null,
    'Viscose canelada', null),

  ('KLS-0006', 'blazer-oversized-tinta', 'Blazer Oversized Tinta',
    (select id from public.categories where slug = 'casacos'),
    329.90, null,
    'Ombros marcados, forro de cetim e cor tinta profunda. O blazer que faz o look sozinho.',
    7, false, false, true,
    array['P','M','G'],
    '[{"name":"Tinta","hex":"#1a2340"}]'::jsonb,
    null, null, null,
    'Poliéster técnico com forro em cetim', null),

  ('KLS-0007', 'conjunto-linho-creme', 'Conjunto Linho Creme',
    (select id from public.categories where slug = 'conjuntos'),
    269.90, null,
    'Camisa e bermuda em linho puro cor de creme fresco. A dupla de verão que respira com você.',
    0, false, false, true,
    array['P','M','G'],
    '[{"name":"Creme","hex":"#e8dfd0"}]'::jsonb,
    null, null, null,
    '100% Linho', null),

  ('KLS-0008', 'vestido-longo-fenda-cereja', 'Vestido Longo Fenda Cereja',
    (select id from public.categories where slug = 'vestidos'),
    359.90, null,
    'Vermelho cereja profundo, alcinhas finas e fenda até a coxa. Para as noites que pedem presença.',
    6, true, false, true,
    array['PP','P','M','G'],
    '[{"name":"Cereja","hex":"#7a1e2b"}]'::jsonb,
    null, null, null,
    'Cetim com elastano', null),

  ('KLS-0101', 'rubra-edp-50ml', 'Rubra Eau de Parfum 50ml',
    (select id from public.categories where slug = 'perfumes'),
    249.90, null,
    'Um floral âmbar que abre com pimenta rosa e bergamota, floresce em rosa turca e jasmim, e assina com âmbar, baunilha e almíscar. Envolvente do primeiro spray à última hora.',
    42, false, true, true,
    null, null,
    array['30ml','50ml','100ml'],
    '{"familia":"floral","topo":["Pimenta rosa","Bergamota","Cassis"],"coracao":["Rosa turca","Jasmim","Pêssego"],"fundo":["Âmbar","Baunilha","Almíscar branco"],"fixacao":"8–10 horas","projecao":"Média-alta","ocasiao":"Noite, encontros, ocasiões especiais"}'::jsonb,
    null, null, null),

  ('KLS-0102', 'layali-al-sharq', 'Layali Al Sharq Oriental Intenso',
    (select id from public.categories where slug = 'perfumes'),
    189.90, null,
    'Uma noite árabe em frasco: incenso, oud suave, mel escuro e resinas doces. Pele quente, memória longa.',
    28, false, false, true,
    null, null,
    array['50ml','100ml'],
    '{"familia":"oriental","topo":["Açafrão","Cardamomo"],"coracao":["Oud","Rosa damascena","Mel"],"fundo":["Âmbar","Benjoim","Baunilha"],"fixacao":"10–12 horas","projecao":"Alta","ocasiao":"Noite, inverno, ocasiões marcantes"}'::jsonb,
    null, null, null),

  ('KLS-0103', 'nevoa-capilar-flor-laranjeira', 'Névoa Capilar Flor de Laranjeira',
    (select id from public.categories where slug = 'perfumes'),
    89.90, null,
    'Uma bruma leve para os cabelos: flor de laranjeira, neroli e um véu de almíscar. Perfume que segue você quando o vento passa.',
    60, false, false, true,
    null, null,
    array['120ml'],
    '{"familia":"floral","topo":["Neroli","Bergamota"],"coracao":["Flor de laranjeira","Jasmim sambac"],"fundo":["Almíscar branco","Cedro"],"fixacao":"4–6 horas","projecao":"Suave","ocasiao":"Dia a dia, verão"}'::jsonb,
    null, null, null),

  ('KLS-0104', 'vetiver-noir-100ml', 'Vetiver Noir 100ml',
    (select id from public.categories where slug = 'perfumes'),
    279.90, null,
    'Vetiver defumado, couro macio e um fio de tabaco doce. Sofisticação sem esforço, para peles que gostam de deixar rastro.',
    18, true, false, true,
    null, null,
    array['50ml','100ml'],
    '{"familia":"amadeirado","topo":["Bergamota","Cardamomo"],"coracao":["Vetiver do Haiti","Íris"],"fundo":["Couro","Tabaco doce","Âmbar cinza"],"fixacao":"10+ horas","projecao":"Alta","ocasiao":"Noite, inverno"}'::jsonb,
    null, null, null),

  ('KLS-0105', 'kit-rubra', 'Kit Rubra — Eau de Parfum + Body Splash',
    (select id from public.categories where slug = 'kits'),
    319.90, 379.80,
    'O ritual completo de Rubra: eau de parfum 50ml + body splash 200ml para camadas de perfume que duram o dia inteiro.',
    22, false, false, true,
    null, null,
    array['Kit'],
    '{"familia":"floral","topo":["Pimenta rosa","Bergamota"],"coracao":["Rosa turca","Jasmim"],"fundo":["Âmbar","Baunilha","Almíscar"],"fixacao":"Camadas · o dia todo","projecao":"Média-alta","ocasiao":"Presente, ritual completo"}'::jsonb,
    null, null, null),

  ('KLS-0201', 'manteiga-corporal-karite-48h', 'Manteiga Corporal Karité 48h',
    (select id from public.categories where slug = 'corpo'),
    79.90, null,
    'Manteiga densa de karité e óleo de amêndoas doces com hidratação clínica de 48 horas. Toque aveludado, sem pegajoso.',
    55, false, true, true,
    null, null,
    array['200ml'], null,
    array['Manteiga de karité 15%','Óleo de amêndoas doces','Pantenol','Vitamina E'],
    null, null),

  ('KLS-0202', 'serum-vitamina-c-10', 'Sérum Vitamina C 10%',
    (select id from public.categories where slug = 'rosto'),
    119.90, null,
    'Vitamina C estabilizada 10% + ácido ferúlico para brilho de manhã e antioxidação o dia inteiro. Textura fluida, absorção imediata.',
    40, false, false, true,
    null, null,
    array['30ml'], null,
    array['Vitamina C 10% (etil ascórbico)','Ácido ferúlico','Vitamina E','Niacinamida 2%'],
    null, null),

  ('KLS-0203', 'sabonete-vegetal-ameixa-negra', 'Sabonete Vegetal Ameixa Negra',
    (select id from public.categories where slug = 'banho'),
    34.90, null,
    'Sabonete em barra com óleos vegetais e extrato de ameixa negra. Espuma cremosa, aroma frutal aveludado, deixa um véu de perfume na pele.',
    120, false, false, true,
    null, null,
    array['120g'], null,
    array['Óleo de coco','Manteiga de cacau','Extrato de ameixa'],
    null, null),

  ('KLS-0204', 'mascara-labial-overnight', 'Máscara Labial Overnight',
    (select id from public.categories where slug = 'labios'),
    59.90, null,
    'Bálsamo de dormir com manteiga de manga e óleo de rosa mosqueta. Você deita, ele repara. Você acorda, seus lábios agradecem.',
    44, true, false, true,
    null, null,
    array['15g'], null,
    array['Manteiga de manga','Óleo de rosa mosqueta','Ceramida NP','Ácido hialurônico'],
    null, null),

  ('KLS-0205', 'bruma-facial-hidratante', 'Bruma Facial Hidratante',
    (select id from public.categories where slug = 'rosto'),
    69.90, null,
    'Água floral de rosa damascena com ácido hialurônico. Um refresco entre as camadas, um respiro no meio da tarde.',
    68, false, false, true,
    null, null,
    array['100ml'], null,
    array['Água floral de rosa','Ácido hialurônico','Pantenol','Aloe vera'],
    null, null)
on conflict (ref) do nothing;
